import os, json, requests, datetime
from pathlib import Path
import frontmatter

PAGE_ID = os.environ['FB_PAGE_ID']
TOKEN = os.environ['FB_PAGE_TOKEN']
GRAPH = "https://graph.facebook.com/v19.0"

# Load Meadow settings
meadow = frontmatter.load('MEADOW.md')
reply_template = meadow['templates']['reply_template']

# Load existing fans
fans_file = Path('fans.json')
fans = json.loads(fans_file.read_text()) if fans_file.exists() else {}

# Get posts from last 24h
posts_url = f"{GRAPH}/{PAGE_ID}/posts?fields=id,message,created_time&limit=25&access_token={TOKEN}"
posts = requests.get(posts_url).json().get('data', [])

replies_needed = []

for post in posts:
    post_id = post['id']
    comments_url = f"{GRAPH}/{post_id}/comments?fields=from,message,created_time&access_token={TOKEN}"
    comments = requests.get(comments_url).json().get('data', [])

    for c in comments:
        name = c['from']['name']
        msg = c['message']
        uid = c['from']['id']

        # Update fan record
        if uid not in fans:
            fans[uid] = {"name": name, "first_seen": c['created_time'][:10], "comments": 0, "last_comment": ""}
        fans[uid]['comments'] += 1
        fans[uid]['last_comment'] = msg[:100]
        fans[uid]['last_seen'] = c['created_time'][:10]

        # Flag for reply if we haven't
        replies_needed.append({
            "name": name,
            "comment": msg,
            "post_id": post_id,
            "suggested_reply": reply_template.replace("{name}", name.split()[0])
        })

# Save
fans_file.write_text(json.dumps(fans, indent=2))

# Build REPLIES_NEEDED.md
md = "# REPLIES_NEEDED\n> Auto-generated by JHAMMERZ_OS\n\n"
md += f"**{len(replies_needed)} comments need love:**\n\n"
for r in replies_needed[:20]: # Cap at 20 per run
    md += f"### {r['name']}\n"
    md += f"> {r['comment']}\n\n"
    md += f"**Suggested**: {r['suggested_reply']}\n"
    md += f"Post: https://facebook.com/{r['post_id']}\n\n---\n"

Path('REPLIES_NEEDED.md').write_text(md)
print(f"Meadow: Processed {len(replies_needed)} comments. {len(fans)} total fans tracked.")
